version: '3.5'
volumes:
  database:
  backend_modules:
  frontend_modules:
  pgadmin:
  avatar:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./avatarStorage
services:
  db:
    image: postgres
    container_name: database
    env_file: .env
    volumes:
      - "database:/var/lib/postgresql/data"
    networks:
      - default
    ports:
      - "5432:5432"
    restart: always
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - avatar:/usr/src/app/avatarStorage
      - ./backend:/usr/src/app
      - backend_modules:/usr/src/app/node_modules
    networks:
      - default
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - avatar:/usr/src/app/src/assets
      - ./frontend:/usr/src/app
      - frontend_modules:/usr/src/app/node_modules
    networks:
      - default
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    logging:
      driver: none
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '5050:80'
    depends_on:
      - db
networks:
  default:
